import { useEffect, useMemo, useState } from 'react';
import { ChannelCatalogResponse, ChannelMetadata, ChannelVideo } from '../types';
import { getChannel, getChannelVideos, getCachedVideoAnalysis } from '../services/api';
import { RequestError, RequestErrorDetails } from './RequestError';

export function ChannelOverview({ channelId, onBack, onOpenAnalysis, onAnalyze }: { channelId: string; onBack: () => void; onOpenAnalysis: (data: any, fromChannel: boolean) => void; onAnalyze: (url: string) => void }) {
  const [channel, setChannel] = useState<ChannelMetadata | null>(null); const [catalog, setCatalog] = useState<ChannelCatalogResponse | null>(null);
  const [videos, setVideos] = useState<ChannelVideo[]>([]); const [nextPageToken, setNextPageToken] = useState<string | undefined>(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'all' | 'analyzed' | 'not'>('all'); const [error, setError] = useState<RequestErrorDetails | null>(null); const [loadingMore, setLoadingMore] = useState(false);
  const load = async (token?: string) => { try { const data = await getChannelVideos(channelId, token); setCatalog((current) => current || data); setVideos((current) => token ? [...current, ...data.videos] : data.videos); setNextPageToken(data.nextPageToken); } catch (err) { setError(err as RequestErrorDetails); } };
  useEffect(() => { void getChannel(channelId).then(setChannel).catch((err) => setError(err)); void load(); }, [channelId]);
  const shown = useMemo(() => videos.filter((video) => (filter === 'all' || (filter === 'analyzed' ? video.insight.analyzed : !video.insight.analyzed)) && video.title.toLowerCase().includes(query.toLowerCase())), [videos, filter, query]);
  const counts = { all: videos.length, analyzed: videos.filter((v) => v.insight.analyzed).length, not: videos.filter((v) => !v.insight.analyzed).length };
  if (error) return <div className="channel-view"><button className="header-back-button" onClick={onBack}>← Back</button><RequestError error={error} onRetry={() => { setError(null); void load(); }} /></div>;
  return <div className="channel-view">
    <button className="header-back-button" onClick={onBack}>← Back</button>
    {!channel ? <div className="channel-skeleton">Loading channel overview…</div> : <section className="channel-header"><img src={channel.thumbnailUrl} alt="" /><div><p className="tagline">CHANNEL</p><h1>{channel.title}</h1>{channel.handle && <p>{channel.handle}</p>}<p className="channel-meta">{channel.subscriberCount && `${Number(channel.subscriberCount).toLocaleString()} subscribers · `}{channel.videoCount && `${Number(channel.videoCount).toLocaleString()} public videos`}</p></div></section>}
    {!catalog ? <div className="channel-skeleton">Loading channel learning overview…</div> : <><section className="channel-overview"><h2>Channel learning overview</h2><p>Based on {catalog.overview.analyzedVideos} analyzed videos</p>{catalog.overview.analyzedVideos < 2 ? <div className="channel-empty"><strong>No channel insights yet.</strong><span>Analyze a few videos to start seeing cross-video patterns.</span></div> : <><div className="channel-summary-grid">{catalog.overview.cards.map((card) => <div key={card.key}><strong>{card.value}</strong><span>{card.label}</span></div>)}</div>{catalog.concepts.length > 0 && <div className="channel-concepts"><h3>Recurring learning friction</h3>{catalog.concepts.map((concept) => <p key={concept.concept}><strong>{concept.concept}</strong><span>{concept.videos} videos · {concept.learners} learners</span></p>)}</div>}</>}</section>
    <section className="channel-videos"><h2>Channel videos</h2><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search videos..." aria-label="Search loaded channel videos" /><div className="channel-filters">{([['all', 'All'], ['analyzed', 'Analyzed'], ['not', 'Not analyzed']] as const).map(([key, label]) => <button key={key} className={filter === key ? 'active' : ''} onClick={() => setFilter(key)}>{label} ({counts[key]})</button>)}</div>{shown.length === 0 ? <div className="channel-empty">{videos.length ? 'No matching videos.' : 'No public videos found.'}</div> : <div className="channel-list">{shown.map((video) => <ChannelVideoRow key={video.videoId} video={video} onOpenAnalysis={onOpenAnalysis} onAnalyze={onAnalyze} />)}</div>}{nextPageToken && <button className="load-more" disabled={loadingMore} onClick={() => { setLoadingMore(true); void load(nextPageToken).finally(() => setLoadingMore(false)); }}>{loadingMore ? 'Loading videos…' : 'Load more videos'}</button>}</section></>}
  </div>;
}
function ChannelVideoRow({ video, onOpenAnalysis, onAnalyze }: { video: ChannelVideo; onOpenAnalysis: (data: any, fromChannel: boolean) => void; onAnalyze: (url: string) => void }) {
  const [loading, setLoading] = useState(false); const youtubeUrl = `https://www.youtube.com/watch?v=${encodeURIComponent(video.videoId)}`;
  const view = async () => { setLoading(true); try { onOpenAnalysis(await getCachedVideoAnalysis(video.videoId), true); } finally { setLoading(false); } };
  return <article className="channel-video-row"><a href={youtubeUrl} target="_blank" rel="noopener noreferrer"><img src={video.thumbnailUrl} alt="" /></a><div><a className="channel-video-title" href={youtubeUrl} target="_blank" rel="noopener noreferrer">{video.title}</a><p>{new Date(video.publishedAt).toLocaleDateString()} · {video.viewCount && `${Number(video.viewCount).toLocaleString()} views`} {video.commentCount && `· ${Number(video.commentCount).toLocaleString()} comments`}</p>{video.insight.analyzed ? <><span className="status-analyzed">✓ Analyzed</span><small>{video.insight.learningPatterns} learning patterns · {video.insight.needsResponse} need response</small></> : <span className="status-not-analyzed">Not analyzed</span>}</div><button className="channel-action" disabled={loading} onClick={() => video.insight.analyzed ? void view() : onAnalyze(youtubeUrl)}>{loading ? 'Loading…' : video.insight.analyzed ? 'View analysis →' : 'Analyze video'}</button></article>;
}
