import { useEffect, useState } from 'react';
import { generateResponseDraft, getResponseWorkflow, setResponseWorkflowResolution } from '../services/api';
import { ResponseWorkflowItem, ResponseWorkflowResponse } from '../types';
import { LearnTraceIcon } from './LearnTraceIcon';

export function ResponseWorkflowView({ videoId }: { videoId: string }) {
  const [data, setData] = useState<ResponseWorkflowResponse | null>(null);
  const [open, setOpen] = useState(false);
  const [tab, setTab] = useState<'needs' | 'resolved'>('needs');
  const [selected, setSelected] = useState<ResponseWorkflowItem | null>(null);
  const [draft, setDraft] = useState(''); const [working, setWorking] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = () => getResponseWorkflow(videoId).then(setData).catch((err) => setError(err instanceof Error ? err.message : 'Could not load response workflow.'));
  useEffect(() => { setOpen(false); setSelected(null); setDraft(''); setError(null); void load(); }, [videoId]);
  const items = tab === 'needs' ? data?.needsResponse || [] : data?.resolved || [];
  const choose = (item: ResponseWorkflowItem) => { setSelected(item); setDraft(''); setError(null); };
  const createDraft = async (regenerate = false) => { if (!selected) return; setWorking(true); setError(null); try { const result = await generateResponseDraft(videoId, selected.workflowId, regenerate); setDraft(result.draft?.draft_text || ''); } catch (err) { setError(err instanceof Error ? err.message : 'Could not create draft.'); } finally { setWorking(false); } };
  const resolve = async (resolved: boolean) => { if (!selected) return; setWorking(true); try { await setResponseWorkflowResolution(videoId, selected.workflowId, resolved); await load(); setSelected({ ...selected, resolutionStatus: resolved ? 'resolved' : 'needs_response' }); } catch (err) { setError(err instanceof Error ? err.message : 'Could not update status.'); } finally { setWorking(false); } };
  const summary = data?.summary;
  const needsCount = summary?.needsResponse ?? 0;
  return <>
    <section className="response-workflow-entry"><button type="button" onClick={() => setOpen(!open)}><span className="response-workflow-icon"><LearnTraceIcon name="messages" /></span><span><b>Needs a response</b><small>{summary ? `${needsCount} conversation${needsCount === 1 ? '' : 's'} to review` : 'Load response workflow'}</small></span><strong>Review ›</strong></button></section>
    {open && <section className="response-workflow-panel"><div className="category-panel-heading"><div><span className="category-detail-label"><LearnTraceIcon name="messages" size={16} /> Needs a response</span><h3>Meaningful learner conversations that may still need your attention.</h3></div><button type="button" className="text-button" onClick={() => setOpen(false)}>Close</button></div>{!summary ? <p className="workflow-empty">{error || 'Loading response workflow…'}</p> : <><div className="workflow-tabs"><button className={tab === 'needs' ? 'active' : ''} onClick={() => setTab('needs')}>Needs response <b>{summary.needsResponse}</b></button><button className={tab === 'resolved' ? 'active' : ''} onClick={() => setTab('resolved')}>Resolved <b>{summary.resolved}</b></button></div>{items.length ? <div className="workflow-list">{items.map((item) => <button type="button" key={item.workflowId} className={`workflow-row workflow-${item.priority}`} onClick={() => choose(item)}><em>{item.priority}</em><strong>{item.title}</strong><p>{item.normalizedNeed || 'Review the supporting learner comments.'}</p><small>{item.supportingCommentIds.length} learner{item.supportingCommentIds.length === 1 ? '' : 's'} · {item.sourceCategory.replace('_', ' ')}</small><span>Draft reply ›</span></button>)}</div> : <p className="workflow-empty">No actionable learner conversations need a response yet.</p>}</>}</section>}
    {selected && <aside className="insight-drawer workflow-drawer"><button type="button" className="drawer-close" onClick={() => setSelected(null)} aria-label="Close"><LearnTraceIcon name="close" /></button><span className="drawer-badge">NEEDS A RESPONSE</span><h2>{selected.title}</h2><p className="drawer-meta">{selected.supportingCommentIds.length} learner{selected.supportingCommentIds.length === 1 ? '' : 's'} raised this · {selected.suggestedResponseType}</p><section className="drawer-section"><h3><LearnTraceIcon name="comment" size={18} /> What learners are asking</h3><blockquote>{selected.normalizedNeed || selected.evidence[0]?.comment_text}</blockquote>{selected.evidence.length > 1 && <details><summary>See supporting comments</summary>{selected.evidence.slice(1).map((item) => <p className="drawer-evidence" key={item.comment_id}>{item.comment_text}</p>)}</details>}</section><section className="drawer-section"><h3><LearnTraceIcon name="reply" size={18} /> Suggested response type</h3><p>{selected.suggestedResponseType}</p><button type="button" className="primary-action" onClick={() => void createDraft(false)} disabled={working}>{working ? 'Preparing draft…' : draft ? 'Use cached draft' : 'Draft reply'}</button>{draft && <><textarea value={draft} onChange={(event) => setDraft(event.target.value)} maxLength={900} aria-label="Editable reply draft" /><div className="drawer-actions"><button type="button" onClick={() => void createDraft(true)} disabled={working}>Regenerate</button><button type="button" onClick={() => void navigator.clipboard?.writeText(draft)}>Copy reply</button></div></>}</section><section className="drawer-section"><button type="button" className="text-button" onClick={() => void resolve(selected.resolutionStatus !== 'resolved')} disabled={working}>{selected.resolutionStatus === 'resolved' ? 'Undo resolved' : 'Mark resolved'}</button></section>{error && <p className="drawer-error">{error}</p>}</aside>}
  </>;
}
